[meta]
name = "Chat Processor"
description = "API to hook and change clients name and message strings"
author = "Drixevel"

[source]
type = "git"
repository = "https://github.com/JoinedSenses/SourceMod-IncludeLibrary.git"
patterns = [
	"include/chat-processor.inc",
]
