[meta]
name = "DHooks Detour"
description = "Dynamic hooking w/ dynamic detouring support"
author = "Drifter321 & Peacemaker"

[source]
type = "git"
repository = "https://github.com/peace-maker/DHooks2.git"
patterns = [
	"sourcemod/scripting/include/dhooks.inc"
]
