name: Documentation

on:
  schedule:
    # Run once every week on Sunday
    - cron: 0 0 * * 0
  push:
    paths:
      # Or if an include has been updated
      - 'includes/*.toml'
      # Manual trigger
      - 'trigger.txt'

jobs:
  documentation:
    name: Build Documentations

    runs-on: ubuntu-latest

    steps:
      - name: Checkout manifests
        uses: actions/checkout@v2

      - name: Download Chumbucket
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "sourcemod-dev/docgen"
          version: "tags/cb-0.1.0"
          file: "chumbucket"

      - name: Chumbucket +x
        run: sudo chmod +x chumbucket

      - name: Create docs directory
        run: mkdir docs

      - name: Process manifests
        run: |
          for i in includes/*.toml; do
            [ -f "$i" ] || break
            export manifest_file=$(basename -- "$i")

            ./chumbucket includes/$manifest_file -o docs/${manifest_file%.*}.bundle
          done

      - name: Upload documentations
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs/
